export const AuthActionTypes = {
    LOGIN_USER: 'LOGIN_USER',
    SIGNUP_USER: 'SIGNUP_USER',
    VERIFY_EMAIL: 'VERIFY_EMAIL',
    AUTH_RESET:"AUTH_RESET",
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
    AUTH_API_RESPONSE_SUCCESS: 'AUTH_API_RESPONSE_SUCCESS',
    AUTH_API_RESPONSE_ERROR: 'AUTH_API_RESPONSE_ERROR',
};
