export const BookingUser = {

    CREATE_BOOKING_FIRST: '@@/BookingUser/CREATE_BOOKING_FIRST',
    CREATE_BOOKING_LOADING: '@@/BookingUser/CREATE_BOOKING_LOADING',
    CREATE_BOOKING_SUCCESS: '@@/BookingUser/CREATE_BOOKING_SUCCESS',
    CREATE_BOOKING_ERROR: '@@/BookingUser/CREATE_BOOKING_ERROR',
    CREATE_BOOKING_RESET: '@@/BookingUser/CREATE_BOOKING_RESET',

    GET_BOOKING_FIRST: '@@/BookingUser/GET_BOOKING_FIRST',
    GET_BOOKING_LOADING: '@@/BookingUser/GET_BOOKING_LOADING',
    GET_BOOKING_SUCCESS: '@@/BookingUser/GET_BOOKING_SUCCESS',
    GET_BOOKING_ERROR: '@@/BookingUser/GET_BOOKING_ERROR',
    GET_BOOKING_RESET: '@@/BookingUser/GET_BOOKING_RESET',

    UPDATE_BOOKING_FIRST: '@@/BookingUser/UPDATE_BOOKING_FIRST',
    UPDATE_BOOKING_LOADING: '@@/BookingUser/UPDATE_BOOKING_LOADING',
    UPDATE_BOOKING_SUCCESS: '@@/BookingUser/UPDATE_BOOKING_SUCCESS',
    UPDATE_BOOKING_ERROR: '@@/BookingUser/UPDATE_BOOKING_ERROR',
    UPDATE_BOOKING_RESET: '@@/BookingUser/UPDATE_BOOKING_RESET',


    CANCEL_BOOKING_FIRST: '@@/BookingUser/CANCEL_BOOKING_FIRST',
    CANCEL_BOOKING_LOADING: '@@/BookingUser/CANCEL_BOOKING_LOADING',
    CANCEL_BOOKING_SUCCESS: '@@/BookingUser/CANCEL_BOOKING_SUCCESS',
    CANCEL_BOOKING_ERROR: '@@/BookingUser/CANCEL_BOOKING_ERROR',
    CANCEL_BOOKING_RESET: '@@/BookingUser/CANCEL_BOOKING_RESET',
}
